/** Open questions:
1. How to perform averages, include days with no data?
 **/


WITH src AS (

    SELECT * FROM datawarehouse.public_tableau.vw_wtv_equipment_pivot

), dim AS (

    SELECT DISTINCT
        CASE WHEN METRIC_TYPE = 'VFA_TIC' THEN 'VFA/TIC' ELSE EQUIPMENT_GROUP END AS EQUIPMENT_GROUP
        , EQUIPMENT_CODE
        , SITE_NAME 
    FROM src
    WHERE 1=1
        AND SITE_NAME = 'Fremont'
        AND (TRIM(Equipment_Group) IN  ('Digester Dosing Volume','Feedstock Storage COD', 'Gas to CHP', 'Gas to Flare') OR TRIM(Equipment_Group) LIKE 'Digester %')

), weekday_metrics AS (

    SELECT 
        d.EQUIPMENT_GROUP 
        , d.EQUIPMENT_CODE
        , d.SITE_NAME
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())-1) as SUNDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())) as MONDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())+1) as TUESDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())+2) as WEDNESDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())+3) as THURSDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())+4) as FRIDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())+5) as SATURDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('week',CURRENT_DATE())-1 AND DATEADD('day',-1,CURRENT_DATE())) as TOTAL_WTD
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('week',DATEADD('week',-1,CURRENT_DATE()))-1 AND DATEADD('week',-1,CURRENT_DATE())-1) as WEEK_MINUS_1_TO_DATE
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('week',DATEADD('week',-2,CURRENT_DATE()))-1 AND DATEADD('week',-2,CURRENT_DATE())-1) as WEEK_MINUS_2_TO_DATE
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('week',DATEADD('week',-1,CURRENT_DATE()))-1 AND DATE_TRUNC('week',DATEADD('week',-1,CURRENT_DATE()))+6) as WEEK_MINUS_1_TOTAL
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('week',DATEADD('week',-2,CURRENT_DATE()))-1 AND DATE_TRUNC('week',DATEADD('week',-2,CURRENT_DATE()))+6) as WEEK_MINUS_2_TOTAL
        , (SELECT COUNT(DISTINCT TO_DATE(RECORD_DATE_LOCAL)) FROM src WHERE RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('week', CURRENT_DATE())-1 AND DATEADD('day',-1,CURRENT_DATE())) as DAYS_WTD
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('month',CURRENT_DATE()) AND DATEADD('day',-1,CURRENT_DATE())) as TOTAL_MTD
        , (SELECT COUNT(DISTINCT TO_DATE(RECORD_DATE_LOCAL)) FROM src WHERE RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('month', CURRENT_DATE()) AND DATEADD('day',-1,CURRENT_DATE())) as DAYS_MTD
        , (SELECT COUNT(DISTINCT TO_DATE(RECORD_DATE_LOCAL)) FROM src WHERE RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('month', CURRENT_DATE()) AND LAST_DAY(CURRENT_DATE(),'month')) as TOTAL_DAYS_IN_MONTH
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATEADD('day',-91,CURRENT_DATE()) AND DATEADD('day',-1,CURRENT_DATE())) as DAILY_AVERAGE_90_DAYS
    FROM dim d



), average_metrics AS (

    SELECT 
        EQUIPMENT_GROUP
        , EQUIPMENT_CODE
        , SITE_NAME
        , SUNDAY 
        , MONDAY
        , TUESDAY
        , WEDNESDAY
        , THURSDAY
        , FRIDAY
        , SATURDAY
        , TOTAL_WTD
        , DIV0(TOTAL_WTD, DAYS_WTD) as CURRENT_WEEK_DAILY_AVERAGE
        , DIV0(DIV0(TOTAL_WTD, DAYS_WTD), DIV0(WEEK_MINUS_1_TO_DATE,DAYS_WTD)) AS PERCENT_TO_PREVIOUS_WEEK
        , WEEK_MINUS_1_TOTAL
        , DIV0(WEEK_MINUS_1_TOTAL,7) AS WEEK_MINUS_1_DAILY_AVERAGE
        , WEEK_MINUS_2_TOTAL
        , DIV0(WEEK_MINUS_2_TOTAL,7) AS WEEK_MINUS_2_DAILY_AVERAGE
        , TOTAL_MTD
        , DIV0(TOTAL_MTD, DAYS_MTD) as CURRENT_MONTH_DAILY_AVERAGE
        , DIV0(TOTAL_MTD, DAYS_MTD)*TOTAL_DAYS_IN_MONTH AS CURRENT_MONTH_RUN_RATE
        , DAILY_AVERAGE_90_DAYS
    FROM weekday_metrics


)

SELECT *
FROM average_metrics