/** Open questions:
1. How to perform averages, include days with no data?

**/


WITH src AS (

    SELECT * FROM datawarehouse.public_tableau.vw_wtv_equipment_pivot

), dim AS (

    SELECT DISTINCT
        CASE WHEN METRIC_TYPE = 'VFA_TIC' THEN 'VFA/TIC' ELSE EQUIPMENT_GROUP END AS EQUIPMENT_GROUP
        , EQUIPMENT_CODE
        , SITE_NAME 
    FROM src
    WHERE 1=1
        AND SITE_NAME = 'Fremont'
        AND TRIM(Equipment_Group) IN  ('Digester Dosing Volume',
                                        'Digester COD',
                                        'Digester ORP', 
                                        'Digester pH',
                                        'Digester TIC',
                                        'Digester VFA', 
                                        'Feedstock Storage COD', 
                                        'Gas to CHP', 
                                        'Gas to Flare',
                                        'CHP Gas Volume In')

), weekday_metrics AS (

    SELECT 
        d.EQUIPMENT_GROUP 
        , d.EQUIPMENT_CODE
        , d.SITE_NAME
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())-1) as SUNDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())) as MONDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())+1) as TUESDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())+2) as WEDNESDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())+3) as THURSDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())+4) as FRIDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL = DATE_TRUNC('week',CURRENT_DATE())+5) as SATURDAY
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('week',CURRENT_DATE())-1 AND DATEADD('day',-1,CURRENT_DATE())) as TOTAL_WTD
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('week',DATEADD('week',-1,CURRENT_DATE()))-1 AND DATEADD('week',-1,CURRENT_DATE())-1) as WEEK_MINUS_1_TO_DATE
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('week',DATEADD('week',-2,CURRENT_DATE()))-1 AND DATEADD('week',-2,CURRENT_DATE())-1) as WEEK_MINUS_2_TO_DATE
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('week',DATEADD('week',-1,CURRENT_DATE()))-1 AND DATE_TRUNC('week',DATEADD('week',-1,CURRENT_DATE()))+6) as WEEK_MINUS_1_TOTAL
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('week',DATEADD('week',-2,CURRENT_DATE()))-1 AND DATE_TRUNC('week',DATEADD('week',-2,CURRENT_DATE()))+6) as WEEK_MINUS_2_TOTAL
        , (SELECT COUNT(DISTINCT TO_DATE(RECORD_DATE_LOCAL)) FROM src WHERE RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('week', CURRENT_DATE())-1 AND DATEADD('day',-1,CURRENT_DATE())) as DAYS_WTD
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('month',CURRENT_DATE()) AND DATEADD('day',-1,CURRENT_DATE())) as TOTAL_MTD
        , (SELECT COUNT(DISTINCT TO_DATE(RECORD_DATE_LOCAL)) FROM src WHERE RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('month', CURRENT_DATE()) AND DATEADD('day',-1,CURRENT_DATE())) as DAYS_MTD
        , (SELECT COUNT(DISTINCT TO_DATE(RECORD_DATE_LOCAL)) FROM src WHERE RECORD_DATE_LOCAL BETWEEN DATE_TRUNC('month', CURRENT_DATE()) AND LAST_DAY(CURRENT_DATE(),'month')) as TOTAL_DAYS_IN_MONTH
        , (SELECT SUM(UNIT_VALUE) FROM src WHERE src.EQUIPMENT_CODE = d.EQUIPMENT_CODE AND src.EQUIPMENT_GROUP = d.EQUIPMENT_GROUP AND src.SITE_NAME = d.SITE_NAME AND src.RECORD_DATE_LOCAL BETWEEN DATEADD('day',-91,CURRENT_DATE()) AND DATEADD('day',-1,CURRENT_DATE())) as TOTAL_90_DAYS
        , (SELECT COUNT(DISTINCT TO_DATE(RECORD_DATE_LOCAL)) FROM src WHERE src.RECORD_DATE_LOCAL BETWEEN DATEADD('day',-91,CURRENT_DATE()) AND DATEADD('day',-1,CURRENT_DATE())) as DAYS_90_DAYS

    FROM dim d



), subtotals AS (

    /** 
    - Need to add records for subtotal calcs in Tableau
    - averages will be true weighted averages of equipment, not a subtotal of the individual averages

    **/
    SELECT 
        CONCAT('Total ', EQUIPMENT_GROUP) AS EQUIPMENT_GROUP
        , NULL AS EQUIPMENT_CODE
        , SITE_NAME
        , SUM(SUNDAY) as SUNDAY
        , SUM(MONDAY) as MONDAY
        , SUM(TUESDAY) as TUESDAY
        , SUM(WEDNESDAY) as WEDNESDAY
        , SUM(THURSDAY) as THURSDAY
        , SUM(FRIDAY) as FRIDAY
        , SUM(SATURDAY) as SATURDAY
        , SUM(TOTAL_WTD) as TOTAL_WTD
        , SUM(WEEK_MINUS_1_TO_DATE) as WEEK_MINUS_1_TO_DATE
        , SUM(WEEK_MINUS_2_TO_DATE) as WEEK_MINUS_2_TO_DATE
        , SUM(WEEK_MINUS_1_TOTAL) as WEEK_MINUS_1_TOTAL
        , SUM(WEEK_MINUS_2_TOTAL) as WEEK_MINUS_2_TOTAL
        , SUM(DAYS_WTD) as DAYS_WTD
        , SUM(TOTAL_MTD) as TOTAL_MTD
        , SUM(DAYS_MTD) as DAYS_MTD
        , SUM(TOTAL_DAYS_IN_MONTH) as TOTAL_DAYS_IN_MONTH
        , SUM(TOTAL_90_DAYS) as TOTAL_90_DAYS
        , SUM(DAYS_90_DAYS) as DAYS_90_DAYS
    
    FROM weekday_metrics
    WHERE 1=1
        AND EQUIPMENT_GROUP IN ('Gas to CHP', 'Gas to Flare')

), average_metrics AS (

    SELECT 
        EQUIPMENT_GROUP
        , EQUIPMENT_CODE
        , SITE_NAME
        , SUNDAY 
        , MONDAY
        , TUESDAY
        , WEDNESDAY
        , THURSDAY
        , FRIDAY
        , SATURDAY
        , TOTAL_WTD
        , DIV0(TOTAL_WTD, DAYS_WTD) as CURRENT_WEEK_DAILY_AVERAGE
        , DIV0(DIV0(TOTAL_WTD, DAYS_WTD), DIV0(WEEK_MINUS_1_TO_DATE,DAYS_WTD)) AS PERCENT_TO_PREVIOUS_WEEK
        , WEEK_MINUS_1_TOTAL
        , DIV0(WEEK_MINUS_1_TOTAL,7) AS WEEK_MINUS_1_DAILY_AVERAGE
        , WEEK_MINUS_2_TOTAL
        , DIV0(WEEK_MINUS_2_TOTAL,7) AS WEEK_MINUS_2_DAILY_AVERAGE
        , TOTAL_MTD
        , DIV0(TOTAL_MTD, DAYS_MTD) as CURRENT_MONTH_DAILY_AVERAGE
        , DIV0(TOTAL_MTD, DAYS_MTD)*TOTAL_DAYS_IN_MONTH AS CURRENT_MONTH_RUN_RATE
        , DIV0(TOTAL_) DAILY_AVERAGE_90_DAYS
    FROM weekday_metrics


)

SELECT *
FROM average_metrics
ORDER BY 1,2,3